### PR TITLE
Updated with Powerlevel10k theme

### PR DESCRIPTION
**Pull request by apurvsinghgautam**
Fastest zsh theme

### CODE REVIEW

**Comment by Tanq16** [comment]
The `sed` for your PR gives an error. Please fix that.

**Comment by apurvsinghgautam** [comment]
Updated the path

**Comment by Tanq16** [comment]
1. Your branch may be behind by a commit.
2. Powerlevel10k needs to be an option given to user. Please add an if condition based on input (eg. accept argument `P` for using powerlevel10k).

**Comment by apurvsinghgautam** [comment]
Condition Added

**Comment by apurvsinghgautam** [comment]
Updated with new sed

**Review by Tanq16 — APPROVED** [review]
Perfect

**Pull request merged**
